// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using WOTCStateSubmission;

namespace WOTCStateSubmission.Migrations.WOTCState
{
    [DbContext(typeof(WOTCStateContext))]
    [Migration("20180125192828_My17thMigration")]
    partial class My17thMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WOTCStateSubmission.Applicant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ApplicantId");

                    b.Property<string>("DateOfBirth");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("MiddleName");

                    b.Property<string>("State");

                    b.Property<string>("StreetAddress");

                    b.Property<int?>("ZipCode");

                    b.Property<string>("city");

                    b.Property<string>("county");

                    b.Property<string>("phoneNumber");

                    b.Property<string>("socialSecurityNumber");

                    b.HasKey("Id");

                    b.ToTable("Applicant");
                });

            modelBuilder.Entity("WOTCStateSubmission.ConditionalCertification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("receivedConditionalCertification");

                    b.HasKey("Id");

                    b.ToTable("ConditionalCertification");
                });

            modelBuilder.Entity("WOTCStateSubmission.Employer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<string>("Ein");

                    b.Property<string>("Email");

                    b.Property<string>("EmployerId");

                    b.Property<string>("LocationId");

                    b.Property<string>("Name");

                    b.Property<string>("State");

                    b.Property<string>("StreetAddress");

                    b.Property<string>("TelephoneNumber");

                    b.Property<int?>("ZipCode");

                    b.HasKey("Id");

                    b.ToTable("Employer");
                });

            modelBuilder.Entity("WOTCStateSubmission.Felony", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("convictionDate");

                    b.Property<bool>("federalConviction");

                    b.Property<bool>("hasFelonyConviction");

                    b.Property<string>("releaseDate");

                    b.HasKey("Id");

                    b.ToTable("Felony");
                });

            modelBuilder.Entity("WOTCStateSubmission.FoodStamps", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("cityReceived");

                    b.Property<bool>("receivedFoodStamps");

                    b.Property<string>("recipientName");

                    b.Property<string>("stateReceived");

                    b.HasKey("Id");

                    b.ToTable("FoodStamps");
                });

            modelBuilder.Entity("WOTCStateSubmission.LongTermUnemployed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("endDate");

                    b.Property<bool>("receivedUnemploymentCompensation");

                    b.Property<string>("startDate");

                    b.Property<string>("stateReceived");

                    b.Property<bool>("unemployed6Months");

                    b.HasKey("Id");

                    b.ToTable("LongTermUnemployed");
                });

            modelBuilder.Entity("WOTCStateSubmission.Ssi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("receivedDisabilityPayments");

                    b.HasKey("Id");

                    b.ToTable("Ssi");
                });

            modelBuilder.Entity("WOTCStateSubmission.Veteran", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("dischargedWithinPastYear");

                    b.Property<bool>("hasServiceConnectedDisablility");

                    b.Property<bool>("unemployedForAtLeast6Months");

                    b.Property<bool>("unemployedLessThan6Months");

                    b.Property<Guid?>("veteranFoodStampsId");

                    b.Property<bool>("veteranOfArmedForces");

                    b.HasKey("Id");

                    b.HasIndex("veteranFoodStampsId");

                    b.ToTable("Veteran");
                });

            modelBuilder.Entity("WOTCStateSubmission.VeteranFoodStamps", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("cityReceived");

                    b.Property<bool>("receivedFoodStamps");

                    b.Property<string>("recipientName");

                    b.Property<string>("stateReceived");

                    b.HasKey("Id");

                    b.ToTable("VeteranFoodStamps");
                });

            modelBuilder.Entity("WOTCStateSubmission.VocationalRehabilitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("completedVocationalRehabilitation");

                    b.Property<bool>("doneByDepartmentOfVeteransAffairs");

                    b.Property<bool>("doneUnderTicketToWork");

                    b.HasKey("Id");

                    b.ToTable("VocationalRehabilitation");
                });

            modelBuilder.Entity("WOTCStateSubmission.Welfare", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("cityReceived");

                    b.Property<bool>("maximizedBenefitsWithinPastTwoYears");

                    b.Property<bool>("receivedBenefits18MonthsWithinPast2Years");

                    b.Property<bool>("receivedBenefitsAtLeast9Months");

                    b.Property<bool>("receivedBenefitsPast18Months");

                    b.Property<bool>("receivedWelfare");

                    b.Property<string>("recipientName");

                    b.Property<string>("stateReceived");

                    b.HasKey("Id");

                    b.ToTable("Welfare");
                });

            modelBuilder.Entity("WOTCStateSubmission.Veteran", b =>
                {
                    b.HasOne("WOTCStateSubmission.VeteranFoodStamps", "veteranFoodStamps")
                        .WithMany()
                        .HasForeignKey("veteranFoodStampsId");
                });
#pragma warning restore 612, 618
        }
    }
}
