// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using WOTCStateSubmission;

namespace WOTCStateSubmission.Migrations.WOTCState
{
    [DbContext(typeof(WOTCStateContext))]
    [Migration("20180125154259_My8th")]
    partial class My8th
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WOTCStateSubmission.Applicant", b =>
                {
                    b.Property<string>("ApplicantId")
                        .HasColumnName("applicantId ")
                        .HasColumnType("nchar(20)");

                    b.Property<string>("DateOfBirth")
                        .HasColumnName("dateOfBirth")
                        .HasColumnType("nchar(10)");

                    b.Property<string>("FirstName")
                        .HasColumnName("firstName")
                        .HasColumnType("nchar(10)");

                    b.Property<string>("LastName")
                        .HasColumnName("lastName")
                        .HasColumnType("nchar(10)");

                    b.Property<string>("MiddleName")
                        .HasColumnName("middleName ")
                        .HasColumnType("nchar(10)");

                    b.Property<string>("State")
                        .HasColumnName("state");

                    b.Property<string>("StreetAddress")
                        .HasColumnName("streetAddress")
                        .HasColumnType("nchar(100)");

                    b.Property<int?>("ZipCode")
                        .HasColumnName("zipCode");

                    b.Property<string>("city")
                        .HasColumnName("city")
                        .HasColumnType("nchar(10)");

                    b.Property<string>("county")
                        .HasColumnName("county");

                    b.Property<string>("phoneNumber")
                        .HasColumnName("phoneNumber");

                    b.Property<string>("socialSecurityNumber")
                        .HasColumnName("socialSecurityNumber")
                        .HasColumnType("nchar(10)");

                    b.HasKey("ApplicantId");

                    b.ToTable("Applicant");
                });

            modelBuilder.Entity("WOTCStateSubmission.Employer", b =>
                {
                    b.Property<string>("EmployerId")
                        .HasColumnName("employerId")
                        .HasColumnType("nchar(20)");

                    b.Property<string>("City")
                        .HasColumnName("city")
                        .HasColumnType("nchar(10)");

                    b.Property<string>("Ein")
                        .HasColumnName("ein")
                        .HasColumnType("nchar(10)");

                    b.Property<string>("Email")
                        .HasColumnName("email");

                    b.Property<string>("LocationId")
                        .HasColumnName("locationId")
                        .HasColumnType("nchar(10)");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("nchar(10)");

                    b.Property<string>("State")
                        .HasColumnName("state")
                        .HasColumnType("nchar(10)");

                    b.Property<string>("StreetAddress")
                        .HasColumnName("streetAddress")
                        .HasColumnType("nchar(100)");

                    b.Property<string>("TelephoneNumber")
                        .HasColumnName("telephoneNumber")
                        .HasColumnType("nchar(10)");

                    b.Property<int?>("ZipCode")
                        .HasColumnName("zipCode");

                    b.HasKey("EmployerId");

                    b.ToTable("Employer");
                });
#pragma warning restore 612, 618
        }
    }
}
